# Generated by Django 3.2.22 on 2023-10-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='proxy',
            field=models.BooleanField(default=False, verbose_name='Proxy requests'),
        ),
        migrations.AlterField(
            model_name='url',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Public redirect'),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.TextField(max_length=2048, verbose_name='URL'),
        ),
    ]
